### ISSUE TITLE
User story

### ISSUE THREAD

**Issue by Naomilounsbury** [nbrown225/Project1#1]
As a traveler, I want to be able to access an application that allows me to find events in a list ordered by date and hotels in the area and the weather for that area so that I can book a hotel and check the weather at the same time.

When I type in a city, and submit, I immediately get event listings and weather for that city for that city
When I click on an event, I can see the details for the event, price, venue and capacity for the event 
and on the same page the 5 closest hotels options to the event will show

**Comment by nbrown225** [comment]
We created the story!
